//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheExchange.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class country
    {
        public country()
        {
            this.category = new HashSet<category>();
        }
    
        public int idcountry { get; set; }
        public string name { get; set; }
        public Nullable<int> idregion { get; set; }
        public string short_description { get; set; }
        public string description { get; set; }
        public string flag_image { get; set; }
        public string banner_image { get; set; }
    
        public virtual region region { get; set; }
        public virtual ICollection<category> category { get; set; }
    }
}
