//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheExchange.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_app_countries
    {
        public int idcustomer_app_countries { get; set; }
        public int idcustomer_app { get; set; }
        public int idcountry { get; set; }
    
        public virtual country country { get; set; }
        public virtual customer_app customer_app { get; set; }
    }
}
