//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheExchange.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public customer()
        {
            this.category_customer = new HashSet<category_customer>();
        }
    
        public int idcustomer { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public System.DateTime startdate { get; set; }
        public string course { get; set; }
        public Nullable<int> idcountry { get; set; }
        public Nullable<int> idcustomer_app { get; set; }
        public string code { get; set; }
        public string position { get; set; }
    
        public virtual ICollection<category_customer> category_customer { get; set; }
        public virtual customer_app customer_app { get; set; }
        public virtual country country { get; set; }
    }
}
