//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheExchange.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_app
    {
        public customer_app()
        {
            this.customer_app_countries = new HashSet<customer_app_countries>();
        }
    
        public int idcustomer_app { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string code { get; set; }
    
        public virtual ICollection<customer_app_countries> customer_app_countries { get; set; }
    }
}
