//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheExchange.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<region> region { get; set; }
        public DbSet<country> country { get; set; }
        public DbSet<category> category { get; set; }
        public DbSet<customer_app> customer_app { get; set; }
        public DbSet<customer_app_countries> customer_app_countries { get; set; }
        public DbSet<category_customer> category_customer { get; set; }
        public DbSet<customer> customer { get; set; }
    }
}
